spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://Trangle:3306/tr_db?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:trangle}
    password: ${SPRING_DATASOURCE_PASSWORD:Trangle@8788583}
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 4
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 1 FROM DUAL
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    com.tr.demo: debug

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true