spring:
  application:
    name: demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://Trangle:3306/tr_db?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:trangle}
    password: ${SPRING_DATASOURCE_PASSWORD:Trangle@8788583}
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com: debug
    org: debug

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

